################
# UsePNG.cmake #
################

FIND_PACKAGE(PNG QUIET)
CANONIFY_BOOL(PNG_FOUND)
MESSAGE(STATUS "libpng found: ${PNG_FOUND}")

IF(PNG_FOUND)
  INCLUDE_DIRECTORIES(${PNG_INCLUDE_DIRS})
  ADD_DEFINITIONS(${PNG_DEFINITIONS})
  ADD_DEFINITIONS(-DUSE_LIBPNG)
ENDIF()
